# Generated by Django 4.1.7 on 2023-03-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
