# Generated by Django 4.1.7 on 2023-03-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project'),
        ),
    ]
