# Generated by Django 4.1.7 on 2023-03-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_comment_commenter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
