# Generated by Django 4.1.7 on 2023-03-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_reportcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='boolean_field',
            field=models.BooleanField(default=False),
        ),
    ]
