# Generated by Django 4.1.7 on 2023-03-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_reportcomment_comment_reportcomment_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomment',
            name='boolean_field',
            field=models.TextField(),
        ),
    ]
